spring:
  application:
    name: Vet Clinic App

  datasource:
    url: "jdbc:mysql://localhost:3306/vet_clinic?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-sender}
    password: ${mail-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
