spring:
  application:
    name: vet-clinic-ap

  datasource:
    url: "jdbc:mysql://localhost:3306/vet_clinic?createDatabaseIfNotExist=true"
    username: "root"
    password: "root"

  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true